[build-system]
requires = ["setuptools >= 77.0.3"]
build-backend = "setuptools.build_meta"

[project]
name = "gcp-airflow-pipeline"
version = "2026.0.1"
requires-python = ">= 3.8"
dependencies = [
  "pandas",
  "apache-airflow-providers-google",
  "google-cloud-storage",
  "google-cloud-bigquery",
]

[tool.setuptools]
package-dir = {"", "src"}

[tool.setuptools.package.find]
where = ["src"]